name: Setup bpftool test
on:
  pull_request:
    paths:
      - 'action.yaml'
      - '.github/workflows/test.yaml'
  push:
    paths:
      - 'action.yaml'
      - '.github/workflows/test.yaml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Install bpftool
      uses: ./
